import 'package:test/test.dart';
import 'package:quantity/number.dart';
import 'package:quantity/src/si/types/absorbed_dose.dart';
import 'package:quantity/src/si/types/absorbed_dose_rate.dart';
import 'package:quantity/src/si/types/acceleration.dart';
import 'package:quantity/src/si/types/activity.dart';
import 'package:quantity/src/si/types/amount_of_substance.dart';
import 'package:quantity/src/si/types/angle.dart';
import 'package:quantity/src/si/types/angular_acceleration.dart';
import 'package:quantity/src/si/types/angular_momentum.dart';
import 'package:quantity/src/si/types/angular_speed.dart';
import 'package:quantity/src/si/types/area.dart';
import 'package:quantity/src/si/types/capacitance.dart';
import 'package:quantity/src/si/types/catalytic_activity.dart';
import 'package:quantity/src/si/types/charge.dart';
import 'package:quantity/src/si/types/charge_density.dart';
import 'package:quantity/src/si/types/concentration.dart';
import 'package:quantity/src/si/types/conductance.dart';
import 'package:quantity/src/si/types/currency.dart';
import 'package:quantity/src/si/types/current.dart';
import 'package:quantity/src/si/types/current_density.dart';
import 'package:quantity/src/si/types/dose_equivalent.dart';
import 'package:quantity/src/si/types/dynamic_viscosity.dart';
import 'package:quantity/src/si/types/electric_field_strength.dart';
import 'package:quantity/src/si/types/electric_flux_density.dart';
import 'package:quantity/src/si/types/electric_potential_difference.dart';
import 'package:quantity/src/si/types/energy.dart';
import 'package:quantity/src/si/types/energy_density.dart';
import 'package:quantity/src/si/types/energy_flux.dart';
import 'package:quantity/src/si/types/entropy.dart';
import 'package:quantity/src/si/types/exposure.dart';
import 'package:quantity/src/si/types/force.dart';
import 'package:quantity/src/si/types/frequency.dart';
import 'package:quantity/src/si/types/heat_flux_density.dart';
import 'package:quantity/src/si/types/illuminance.dart';
import 'package:quantity/src/si/types/inductance.dart';
import 'package:quantity/src/si/types/information.dart';
import 'package:quantity/src/si/types/information_rate.dart';
import 'package:quantity/src/si/types/kinematic_viscosity.dart';
import 'package:quantity/src/si/types/length.dart';
import 'package:quantity/src/si/types/luminance.dart';
import 'package:quantity/src/si/types/luminous_flux.dart';
import 'package:quantity/src/si/types/luminous_intensity.dart';
import 'package:quantity/src/si/types/magnetic_field_strength.dart';
import 'package:quantity/src/si/types/magnetic_flux.dart';
import 'package:quantity/src/si/types/magnetic_flux_density.dart';
import 'package:quantity/src/si/types/mass.dart';
import 'package:quantity/src/si/types/mass_density.dart';
import 'package:quantity/src/si/types/mass_flow_rate.dart';
import 'package:quantity/src/si/types/mass_flux_density.dart';
import 'package:quantity/src/si/types/molar_energy.dart';
import 'package:quantity/src/si/types/molar_entropy.dart';
import 'package:quantity/src/si/types/permeability.dart';
import 'package:quantity/src/si/types/permittivity.dart';
import 'package:quantity/src/si/types/pixel.dart';
import 'package:quantity/src/si/types/pixel_density.dart';
import 'package:quantity/src/si/types/power.dart';
import 'package:quantity/src/si/types/pressure.dart';
import 'package:quantity/src/si/types/radiance.dart';
import 'package:quantity/src/si/types/radiant_intensity.dart';
import 'package:quantity/src/si/types/resistance.dart';
import 'package:quantity/src/si/types/resolution.dart';
import 'package:quantity/src/si/types/scalar.dart';
import 'package:quantity/src/si/types/solid_angle.dart';
import 'package:quantity/src/si/types/specific_energy.dart';
import 'package:quantity/src/si/types/specific_heat_capacity.dart';
import 'package:quantity/src/si/types/specific_volume.dart';
import 'package:quantity/src/si/types/spectral_irradiance.dart';
import 'package:quantity/src/si/types/speed.dart';
import 'package:quantity/src/si/types/surface_tension.dart';
import 'package:quantity/src/si/types/temperature.dart';
import 'package:quantity/src/si/types/temperature_interval.dart';
import 'package:quantity/src/si/types/thermal_conductivity.dart';
import 'package:quantity/src/si/types/time.dart';
import 'package:quantity/src/si/types/time_instant.dart';
import 'package:quantity/src/si/types/token.dart';
import 'package:quantity/src/si/types/token_rate.dart';
import 'package:quantity/src/si/types/torque.dart';
import 'package:quantity/src/si/types/volume.dart';
import 'package:quantity/src/si/types/volume_flow_rate.dart';
import 'package:quantity/src/si/types/wave_number.dart';

void main() {
  group('All Quantity Types Constant Constructors Runtime Execution', () {
    test('constant constructors', () {
      final absorbedDose = AbsorbedDose.constant(Double(5));
      expect(absorbedDose.valueSI.toDouble(), 5.0);
      final absorbedDoseRate = AbsorbedDoseRate.constant(Double(5));
      expect(absorbedDoseRate.valueSI.toDouble(), 5.0);
      final acceleration = Acceleration.constant(Double(5));
      expect(acceleration.valueSI.toDouble(), 5.0);
      final activity = Activity.constant(Double(5));
      expect(activity.valueSI.toDouble(), 5.0);
      final amountOfSubstance = AmountOfSubstance.constant(Double(5));
      expect(amountOfSubstance.valueSI.toDouble(), 5.0);
      final angle = Angle.constant(Double(5), units: Angle.radians);
      expect(angle.valueSI.toDouble(), 5.0);
      final angularAcceleration = AngularAcceleration.constant(Double(5));
      expect(angularAcceleration.valueSI.toDouble(), 5.0);
      final angularMomentum = AngularMomentum.constant(Double(5));
      expect(angularMomentum.valueSI.toDouble(), 5.0);
      final angularSpeed = AngularSpeed.constant(Double(5));
      expect(angularSpeed.valueSI.toDouble(), 5.0);
      final area = Area.constant(Double(5));
      expect(area.valueSI.toDouble(), 5.0);
      final capacitance = Capacitance.constant(Double(5));
      expect(capacitance.valueSI.toDouble(), 5.0);
      final catalyticActivity = CatalyticActivity.constant(Double(5));
      expect(catalyticActivity.valueSI.toDouble(), 5.0);
      final charge = Charge.constant(Double(5));
      expect(charge.valueSI.toDouble(), 5.0);
      final chargeDensity = ChargeDensity.constant(Double(5));
      expect(chargeDensity.valueSI.toDouble(), 5.0);
      final concentration = Concentration.constant(Double(5));
      expect(concentration.valueSI.toDouble(), 5.0);
      final conductance = Conductance.constant(Double(5));
      expect(conductance.valueSI.toDouble(), 5.0);
      final currency = Currency.constant(Double(5));
      expect(currency.valueSI.toDouble(), 5.0);
      final current = Current.constant(Double(5));
      expect(current.valueSI.toDouble(), 5.0);
      final currentDensity = CurrentDensity.constant(Double(5));
      expect(currentDensity.valueSI.toDouble(), 5.0);
      final doseEquivalent = DoseEquivalent.constant(Double(5));
      expect(doseEquivalent.valueSI.toDouble(), 5.0);
      final dynamicViscosity = DynamicViscosity.constant(Double(5));
      expect(dynamicViscosity.valueSI.toDouble(), 5.0);
      final electricFieldStrength = ElectricFieldStrength.constant(Double(5));
      expect(electricFieldStrength.valueSI.toDouble(), 5.0);
      final electricFluxDensity = ElectricFluxDensity.constant(Double(5));
      expect(electricFluxDensity.valueSI.toDouble(), 5.0);
      final electricPotentialDifference =
          ElectricPotentialDifference.constant(Double(5));
      expect(electricPotentialDifference.valueSI.toDouble(), 5.0);
      final energy = Energy.constant(Double(5));
      expect(energy.valueSI.toDouble(), 5.0);
      final energyDensity = EnergyDensity.constant(Double(5));
      expect(energyDensity.valueSI.toDouble(), 5.0);
      final energyFlux = EnergyFlux.constant(Double(5));
      expect(energyFlux.valueSI.toDouble(), 5.0);
      final entropy = Entropy.constant(Double(5));
      expect(entropy.valueSI.toDouble(), 5.0);
      final exposure = Exposure.constant(Double(5));
      expect(exposure.valueSI.toDouble(), 5.0);
      final force = Force.constant(Double(5));
      expect(force.valueSI.toDouble(), 5.0);
      final frequency = Frequency.constant(Double(5));
      expect(frequency.valueSI.toDouble(), 5.0);
      final heatFluxDensity = HeatFluxDensity.constant(Double(5));
      expect(heatFluxDensity.valueSI.toDouble(), 5.0);
      final illuminance = Illuminance.constant(Double(5));
      expect(illuminance.valueSI.toDouble(), 5.0);
      final inductance = Inductance.constant(Double(5));
      expect(inductance.valueSI.toDouble(), 5.0);
      final information = Information.constant(Double(5));
      expect(information.valueSI.toDouble(), 5.0);
      final informationRate = InformationRate.constant(Double(5));
      expect(informationRate.valueSI.toDouble(), 5.0);
      final kinematicViscosity = KinematicViscosity.constant(Double(5));
      expect(kinematicViscosity.valueSI.toDouble(), 5.0);
      final length = Length.constant(Double(5));
      expect(length.valueSI.toDouble(), 5.0);
      final luminance = Luminance.constant(Double(5));
      expect(luminance.valueSI.toDouble(), 5.0);
      final luminousFlux = LuminousFlux.constant(Double(5));
      expect(luminousFlux.valueSI.toDouble(), 5.0);
      final luminousIntensity = LuminousIntensity.constant(Double(5));
      expect(luminousIntensity.valueSI.toDouble(), 5.0);
      final magneticFieldStrength = MagneticFieldStrength.constant(Double(5));
      expect(magneticFieldStrength.valueSI.toDouble(), 5.0);
      final magneticFlux = MagneticFlux.constant(Double(5));
      expect(magneticFlux.valueSI.toDouble(), 5.0);
      final magneticFluxDensity = MagneticFluxDensity.constant(Double(5));
      expect(magneticFluxDensity.valueSI.toDouble(), 5.0);
      final mass = Mass.constant(Double(5));
      expect(mass.valueSI.toDouble(), 5.0);
      final massDensity = MassDensity.constant(Double(5));
      expect(massDensity.valueSI.toDouble(), 5.0);
      final massFlowRate = MassFlowRate.constant(Double(5));
      expect(massFlowRate.valueSI.toDouble(), 5.0);
      final massFluxDensity = MassFluxDensity.constant(Double(5));
      expect(massFluxDensity.valueSI.toDouble(), 5.0);
      final molarEnergy = MolarEnergy.constant(Double(5));
      expect(molarEnergy.valueSI.toDouble(), 5.0);
      final molarEntropy = MolarEntropy.constant(Double(5));
      expect(molarEntropy.valueSI.toDouble(), 5.0);
      final permeability = Permeability.constant(Double(5));
      expect(permeability.valueSI.toDouble(), 5.0);
      final permittivity = Permittivity.constant(Double(5));
      expect(permittivity.valueSI.toDouble(), 5.0);
      final pixel = Pixel.constant(Double(5));
      expect(pixel.valueSI.toDouble(), 5.0);
      final pixelDensity = PixelDensity.constant(Double(5));
      expect(pixelDensity.valueSI.toDouble(), 5.0);
      final power = Power.constant(Double(5));
      expect(power.valueSI.toDouble(), 5.0);
      final pressure = Pressure.constant(Double(5));
      expect(pressure.valueSI.toDouble(), 5.0);
      final radiance = Radiance.constant(Double(5));
      expect(radiance.valueSI.toDouble(), 5.0);
      final radiantIntensity = RadiantIntensity.constant(Double(5));
      expect(radiantIntensity.valueSI.toDouble(), 5.0);
      final resistance = Resistance.constant(Double(5));
      expect(resistance.valueSI.toDouble(), 5.0);
      final resolution = Resolution.constant(Double(5));
      expect(resolution.valueSI.toDouble(), 5.0);
      final scalar = Scalar.constant(Double(5));
      expect(scalar.valueSI.toDouble(), 5.0);
      final solidAngle = SolidAngle.constant(Double(5));
      expect(solidAngle.valueSI.toDouble(), 5.0);
      final specificEnergy = SpecificEnergy.constant(Double(5));
      expect(specificEnergy.valueSI.toDouble(), 5.0);
      final specificHeatCapacity = SpecificHeatCapacity.constant(Double(5));
      expect(specificHeatCapacity.valueSI.toDouble(), 5.0);
      final specificVolume = SpecificVolume.constant(Double(5));
      expect(specificVolume.valueSI.toDouble(), 5.0);
      final spectralIrradiance = SpectralIrradiance.constant(Double(5));
      expect(spectralIrradiance.valueSI.toDouble(), 5.0);
      final speed = Speed.constant(Double(5));
      expect(speed.valueSI.toDouble(), 5.0);
      final surfaceTension = SurfaceTension.constant(Double(5));
      expect(surfaceTension.valueSI.toDouble(), 5.0);
      final temperature = Temperature.constant(Double(5));
      expect(temperature.valueSI.toDouble(), 5.0);
      final temperatureInterval = TemperatureInterval.constant(Double(5));
      expect(temperatureInterval.valueSI.toDouble(), 5.0);
      final thermalConductivity = ThermalConductivity.constant(Double(5));
      expect(thermalConductivity.valueSI.toDouble(), 5.0);
      final time = Time.constant(Double(5));
      expect(time.valueSI.toDouble(), 5.0);
      final timeInstant = TimeInstant.constant(Double(5));
      expect(timeInstant.valueSI.toDouble(), 5.0);
      final token = Token.constant(Double(5));
      expect(token.valueSI.toDouble(), 5.0);
      final tokenRate = TokenRate.constant(Double(5));
      expect(tokenRate.valueSI.toDouble(), 5.0);
      final torque = Torque.constant(Double(5));
      expect(torque.valueSI.toDouble(), 5.0);
      final volume = Volume.constant(Double(5));
      expect(volume.valueSI.toDouble(), 5.0);
      final volumeFlowRate = VolumeFlowRate.constant(Double(5));
      expect(volumeFlowRate.valueSI.toDouble(), 5.0);
      final waveNumber = WaveNumber.constant(Double(5));
      expect(waveNumber.valueSI.toDouble(), 5.0);
    });
  });
}
