name: quantity
version: 0.1.0
description: Physical quantity and number libraries.
author: Rob Bishop (cooler-king)
environment:
  sdk: '>=1.12.0 <2.0.0'
dependencies:
  logging: "^0.11.1"
  quiver: "^0.21.4"
dev_dependencies:
  browser: "^0.10.0"
  test: "^0.12.0"
