name: quantity
version: 1.0.0
description: Facilitates working with physical quantities.
author: Rob Bishop (cooler-king)
homepage: https://github.com/cooler-king/quantity
documentation: https://github.com/cooler-king/quantity/wiki
environment:
  sdk: '>=2.3.0 <3.0.0'
dependencies:
  intl: ^0.15.0
  logging: ^0.11.3
dev_dependencies:
  test: ^1.2.0
