name: quantity
version: 0.1.0
description: Facilitates working with physical quantities.
author: Rob Bishop (cooler-king)
homepage: https://github.com/cooler-king/quantity
documentation: https://github.com/cooler-king/quantity/wiki
environment:
  sdk: '>=1.12.0 <2.0.0'
dependencies:
  intl: "^0.12.4"
  logging: "^0.11.1"
  quiver: "^0.21.4"
dev_dependencies:
  browser: "^0.10.0"
  test: "^0.12.0"
